config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
get '/admin', to: 'static_pages#admin'
get '/slider', to: 'static_pages#slider'
get 'not_allow', to: 'static_pages#not_allow'
get '/admin/user', to: 'static_pages#adminuser', as: "adminuser"
get '/index', to: 'static_pages#index'
get "/about" => 'static_pages#about', as: 'about'
get "/spp" => 'static_pages#spp', as: 'spp'
get "/deletep" => 'static_pages#deletep', as: 'deletep'
get "/setadmin" => 'static_pages#setadmin', as: 'setadmin'
get "/acceptp" => 'static_pages#acceptp', as: 'acceptp'
post "/index" => 'static_pages#searchp'
get "/searchpeople" => 'static_pages#searchpeople', as: 'searchpeople'
get '/signup', to: 'users#new'
post '/signup',  to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
root 'static_pages#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
resources :microposts do
    resources :comments, except: [:show, :edit]
    resources :likes
    resources :save_posts
    
  end
resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_avatar.html.erb
<div class="col-sm-3">
    <div class="panel widget light-widget panel-bd-top">
        <div class="well">
        <div class="text-center vd_info-parent">                 
                <% if @user.picture? %>
                <%= image_tag @user.picture.url ,class: "avatar" if @user.picture?%>
                <% else %>
                <img src="/uploads/s2.jpg" class="avatar">
                <% end %>
            </div>
            <div class="row">
            </div>
            <h2 class="font-semibold mgbt-xs-5"><%= @user.name %></h2>
            <div class="mgtp-20">
                <center>
                    <%= render 'users/follow_form' if logged_in? %><br>
                    <section class="stats">
                        <%= render 'shared/stats' %>
                    </section>
                    <br>
                </center>
                <% if @user.id == current_user.id %>
                <table class="table table-striped table-hover" >
                    <tbody >                        

                        <tr>
                            <td align="center">
                                <i class="fa fa-pencil-square-o" style="color: #1866b1;"></i>
                                <%= link_to "Edit profile", edit_user_path(current_user) %> </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <i class="fa fa-file" style="color: #1866b1;"></i>
                                    <%= link_to "Write post..", new_micropost_path %> </td>
                                </tr>


                            </tbody>
                        </table>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/shared/not_allow.html.erb
<center> You are not allowwed to access this page</center>