config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
get '/admin', to: 'static_pages#admin'
get '/slider', to: 'static_pages#slider'
get 'not_allow', to: 'static_pages#not_allow'
get '/admin/user', to: 'static_pages#adminuser', as: "adminuser"
get '/index', to: 'static_pages#index'
get "/about" => 'static_pages#about', as: 'about'
get "/spp" => 'static_pages#spp', as: 'spp'
get "/deletep" => 'static_pages#deletep', as: 'deletep'
get "/setadmin" => 'static_pages#setadmin', as: 'setadmin'
get "/acceptp" => 'static_pages#acceptp', as: 'acceptp'
post "/index" => 'static_pages#searchp'
get "/searchpeople" => 'static_pages#searchpeople', as: 'searchpeople'
get '/signup', to: 'users#new'
post '/signup',  to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
root 'static_pages#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
resources :microposts do
    resources :comments, except: [:show, :edit]
    resources :likes
    resources :save_posts
    
  end
resources :relationships,       only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  
  belongs_to :user
  belongs_to :district
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture
  validates :user_id, presence: true
  validates :content, presence: true
  validates :title, presence: true
  validates :district_id, presence: true
  validate  :picture_size
  before_save :fix_title

  has_many :comments,  dependent: :destroy
  has_many :likes,  dependent: :destroy
  has_many :save_posts,  dependent: :destroy
  has_many :notifications,  dependent: :destroy
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    def fix_title
      title = self.title
      len= title.length - 1
      res1=''
      start = 0
      if title[0]== ' '
      
      for i in 1..len
        if title[i] != ' '
          title = title[i..len] 
          break
        end
      end
      end
      self.title = title[start..len].capitalize
    end
  end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show, :new]
  before_action :correct_user,   only: [:destroy, :update, :edit]


  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to current_user
    else
      @feed_items = []
      flash[:danger] = "failed ! input field can't be blank"
      redirect_to current_user
    end
  end
  def show
    #delete notification
    @ownNotifications= Notification.where("user_id = ? and micropost_id = ?",current_user.id,params[:id])
    @ownNotifications.each do |noti|
      noti.destroy
    end
    #end delete
    @user = User.find(current_user.id)
    @marked= SavePost.where("user_id = ? and micropost_id = ?",current_user.id,params[:id])
    @liked= Like.where("user_id= ? and micropost_id = ?",current_user.id,params[:id])
    @micropost = Micropost.find(params[:id])
    @notifications= @user.notifications
    @comments = @micropost.comments
    @likes= @micropost.likes
    @new_comment = @micropost.comments.new
    @new_like = @micropost.likes.new
    @new_save_post = @micropost.save_posts.new
  end
  
  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      flash[:success] = "Post updated"
      redirect_to @micropost
    else
      flash[:danger] = "failed ! input field can't be blank"
      redirect_to @micropost
    end
  end

  def edit
    @user = User.find(current_user.id)
    @notifications= @user.notifications
    @micropost = Micropost.find(params[:id])
    @districts = District.all
  end

  def destroy
    @user = User.find(current_user.id)
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to @user
  end
  def new
    @notifications= current_user.notifications
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
     @user = User.find(current_user.id)
     @districts = District.all
    
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture, :title, :district_id)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
	
end

app/views/microposts/_form_new.html.erb
<div id="edit-user" class="tab-pane active">
    <div class="col-md-9 personal-info">
       
              <div class=" well" style="margin-left: 20px; margin-right: 20px">
                <%= form_for(@micropost) do |f| %>
                <div id="clock">
                    <img id ='image1' src="<%= @micropost.picture.url %>"  width="100%" height="300">
                </div>
                <div class="form-group">
                    <label for="telephone">Image :</label>
                    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
                </div>
                <div class="form-group">
                    <%= f.text_field :title, class: 'form-control',placeholder: "Title" %>
                </div>
                <div class="form-group">  
                
                <%= f.select :district_id, @districts.map{ |c| [c.name, c.id] },
                {include_blank: t(".choose_address")},
                {class: "form-control"} %>
                        


    </div>
    
<%= f.text_area :content, placeholder: "Compose new post...", size: "24x6" %>
<button type="submit" class="btn btn-primary">Submit</button>

<% end %>
</div>



<script>
  $(document).ready(function () {
    $('#image1').attr('src');
    console.log($('#image1').attr('src'));
    $('input[name="micropost[picture]"]').on('change',function () {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#image1').attr('src', e.target.result);
      }
      reader.readAsDataURL(this.files[0]);
  }
})
})
</script>


</div>
</div>

app/views/microposts/_index.html.erb
<div class="container">


    <div class="row">
        <div style="width: 800px;">
            <div class="panel panel-default">
                <div class="panel-heading c-list">
                    <span class="title">all users</span>
                    
                </div>
                
                <div class="row" >
                    <div class="col-xs-12">
                        <div class="input-group c-search">
                            <input type="text" class="form-control" id="contact-list-search">
                            
                        </div>
                    </div>
                </div>
                
                <ul class="list-group" id="contact-list">
                    <% @users.each do |user| %>
                    <li class="list-group-item">
                        <div class="col-xs-12 col-sm-1">
                            <% if user.picture? %>
                            <%= image_tag user.picture.url ,style:"width: 50px;height:50px;",class: "img-circle" %>
                            <% else %>
                            <img src="images/s2.jpg" class="img-circle" height="50", width="50">
                            <% end %>
                        </div>
                        

                        
                    </li>
                    <% end %>
                    
                </ul>
            </div>
        </div>
    </div>
    
    <div id="cant-do-all-the-work-for-you" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Ooops!!!</h4>
                </div>
                <div class="modal-body">
                    <p>I am being lazy and do not want to program an "Add User" section into this snippet... So it looks like you'll have to do that for yourself.</p><br/>
                    <p><strong>Sorry<br/>
                        ~ Mouse0270</strong></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- JavaScrip Search Plugin -->
        <script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>

    </div>
    <style type="text/css">
        @import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);

        body {
            padding: 30px 0px 60px;
        }
        .panel > .list-group .list-group-item:first-child {
            /*border-top: 1px solid rgb(204, 204, 204);*/
        }
        @media (max-width: 767px) {
            .visible-xs {
                display: inline-block !important;
            }
            .block {
                display: block !important;
                width: 100%;
                height: 1px !important;
            }
        }
        #back-to-bootsnipp {
            position: fixed;
            top: 10px; right: 10px;
        }


        .c-search > .form-control {
           border-radius: 0px;
           border-width: 0px;
           border-bottom-width: 1px;
           font-size: 1.3em;
           padding: 12px 12px;
           height: 44px;
           outline: none !important;
       }
       .c-search > .form-control:focus {
        outline:0px !important;
        -webkit-appearance:none;
        box-shadow: none;
    }
    .c-search > .input-group-btn .btn {
       border-radius: 0px;
       border-width: 0px;
       border-left-width: 1px;
       border-bottom-width: 1px;
       height: 44px;
   }


   .c-list {
    padding: 0px;
    min-height: 44px;
}
.title {
    display: inline-block;
    font-size: 1.7em;
    font-weight: bold;
    padding: 5px 15px;
}
ul.c-controls {
    list-style: none;
    margin: 0px;
    min-height: 44px;
}

ul.c-controls li {
    margin-top: 8px;
    float: left;
}

ul.c-controls li a {
    font-size: 1.7em;
    padding: 11px 10px 6px;   
}
ul.c-controls li a i {
    min-width: 24px;
    text-align: center;
}

ul.c-controls li a:hover {
    background-color: rgba(51, 51, 51, 0.2);
}

.c-toggle {
    font-size: 1.7em;
}

.name {
    font-size: 1em;
    font-weight: 700;
}

.c-info {
    padding: 5px 10px;
    font-size: 1.25em;
}

</style>
<script type="text/javascript">
    $(function () {
        /* BOOTSNIPP FULLSCREEN FIX */
        if (window.location == window.parent.location) {
            $('#back-to-bootsnipp').removeClass('hide');
        }


        $('[data-toggle="tooltip"]').tooltip();

        $('#fullscreen').on('click', function(event) {
            event.preventDefault();
            window.parent.location = "http://bootsnipp.com/iframe/4l0k2";
        });
        $('a[href="#cant-do-all-the-work-for-you"]').on('click', function(event) {
            event.preventDefault();
            $('#cant-do-all-the-work-for-you').modal('show');
        })

        $('[data-command="toggle-search"]').on('click', function(event) {
            event.preventDefault();
            $(this).toggleClass('hide-search');

            if ($(this).hasClass('hide-search')) {        
                $('.c-search').closest('.row').slideUp(100);
            }else{   
                $('.c-search').closest('.row').slideDown(100);
            }
        })

        $('#contact-list').searchable({
            searchField: '#contact-list-search',
            selector: 'li',
            childSelector: '.name',
            show: function( elem ) {
                elem.slideDown(100);
            },
            hide: function( elem ) {
                elem.slideUp( 100 );
            }
        })
    });

</script>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/_post_detail.html.erb
<div id="edit-user" class="tab-pane active">
  <div class="col-sm-9">  
    <div class="row">
      <div class=" well" style="margin-left: 20px; margin-right: 20px">
        <div align="left">
          <table>
            <tr>
              <td style="padding-right: 20px">
              <% if @micropost.user.picture? %>
                <%= image_tag @micropost.user.picture.url ,class: "img-circle", height:"55", width:"55" if @micropost.user.picture?%>
              <% else %>
                <img src="/uploads/s2.jpg" class= "img-circle", height="55", width="55">
              <% end %>
              </td>
              <td>
                <span class="page-newsfeed-06">
                  <a href="" title=""><%= link_to @micropost.user.name, @micropost.user %></a>                  
                </span>
                <br> 
                <div style="color: #000;">
                  <%= form_for [@micropost, @new_save_post], remote: true do |f| %>
                  <%= time_ago_in_words(@micropost.created_at) %> ago. &nbsp;&nbsp;&nbsp;
                  <i class="fa fa-map-marker"></i>  
                  <a class="tag badge badge-default overflow-hidden">
                    <%= @micropost.district.name %>
                  </a>
                  &nbsp;&nbsp;&nbsp;
                  <% if current_user.id == @micropost.user_id %>
                  <%= link_to "Edit", edit_micropost_path(@micropost),class: "fa fa-pencil" %>
                  &nbsp;&nbsp;&nbsp;
                  <%= link_to @micropost, method: :delete,data: { confirm: "You sure?" } do %>                  
                  <i class="fa fa-trash" >delete</i>
                  <% end %>
                  <% end %>
                  &nbsp;&nbsp;&nbsp;
                  <!-- for form -->
                  <%= f.hidden_field :user_id, value: @user.id %>
                  <%= f.hidden_field :micropost_id, value: @micropost.id %>
                  <% if current_user.id != @micropost.user.id %>
                  <span id="bookmark">
                    <%= render 'save_posts/bookmark', marked: @marked %>
                  </span>
                  <% end %>
                  <% end %>
                </div>
              </td>
            </tr>
          </table>
        </div>
        <img src="<%= @micropost.picture.url %>" alt="Paris" width="100%" height="300">
        <center><h4 class="page-newsfeed-06"> <%= @micropost.title %></h4></center> 
        <p><%= @micropost.content %></p> 
        <hr /> 
        <!-- form like -->
        <%= form_for [@micropost, @new_like], remote: true do |f| %>
        <% result= "#{@user.name} liked your post" %>
        <%= f.hidden_field :notification, value: result %>
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= f.hidden_field :micropost_id, value: @micropost.id %>
        <span id="like">
          <%= render 'likes/button_like', liked: @liked %>
        </span>
        <span id="all-like">
          <%= render 'likes/all_like', likes: @likes %>
        </span>  
        <% end %>
        
        <br>
        <div style="background-color: #f6f7f1">  
          <!-- comment list -->
          <%= form_for [@micropost, @new_comment], remote: true do |f| %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.hidden_field :micropost_id, value: @micropost.id %>
          <%= f.hidden_field :comment, value: "==delete==" %>
          <div id="comments-list">
            <%= render 'comments/comment', comments: @comments %>
          </div>
          <% end %>
          <!-- end comment list -->
          <div id="comment-form">
            <%= render 'comments/comment_form' %>
          </div> <br><br><br> 
        </div>



      </div>



    </div>

  </div>
</div>

app/views/microposts/_tab_name_edit.html.erb
<ul class="nav nav-tabs widget">
	<li class="active"> <a data-toggle="tab" href="#edit-user"> Edit User <span class="menu-active"><i class="fa fa-caret-up"></i></span> </a></li>
	
</ul>

app/views/microposts/edit.html.erb
<% provide(:title, 'Edit post') %>
<% provide(:button_text, 'Save changes') %>


<body style="background: url(images/background/8.jpg)">
    <div class="container-fuild">
       
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3 header-inner">
                        <a href="#"><img src="images/logo.png" alt=""></a>
                    </div>
                </div>
                
                <div class="col-md-12">
                    <div class="row profile">
                        <%= render 'shared/avatar' %>
                        <div class="col-sm-9">
                            <div class="tabs widget">
                                <div class="tab-content">
                                    
                                            
                                    <%= render 'form_new' %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
            
        </div>
    </div>
    <script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
    <script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
    <script type='text/javascript' src='js/camera.min.js'></script> 
    <script src="owlcarousel/owl.carousel.min.js"></script>
    <script src="js/homepage.js"></script>
</body> 

app/views/microposts/new.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>


<body style="background: url(images/background/8.jpg)">
    <div class="container-fuild">
       
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3 header-inner">
                        <a href="#"><img src="images/logo.png" alt=""></a>
                    </div>
                </div>
                
                <div class="col-md-12">
                    <div class="row profile">
                        <%= render 'shared/avatar' %>
                        <div class="col-sm-9">
                            <div class="tabs widget">
                                <div class="tab-content">
                                    
                                            
                                    <%= render 'form_new' %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
            
        </div>
    </div>
    <script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
    <script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
    <script type='text/javascript' src='js/camera.min.js'></script> 
    <script src="owlcarousel/owl.carousel.min.js"></script>
    <script src="js/homepage.js"></script>
</body> 

app/views/microposts/show.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>


<body style="background: url(images/background/8.jpg)">
    <div class="container-fuild">
       
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3 header-inner">
                        <a href="#"><img src="images/logo.png" alt=""></a>
                    </div>
                </div>
                
                <div class="col-md-12">
                    <div class="row profile">
                        <%= render 'shared/avatar' %>
                        <div class="col-sm-9">
                            <div class="tabs widget">
                                <div class="tab-content">
                                    
                                            
                                    <%= render 'post_detail' %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
            
        </div>
    </div>
    <script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
    <script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
    <script type='text/javascript' src='js/camera.min.js'></script> 
    <script src="owlcarousel/owl.carousel.min.js"></script>
    <script src="js/homepage.js"></script>
</body> 