config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
get '/admin', to: 'static_pages#admin'
get '/slider', to: 'static_pages#slider'
get 'not_allow', to: 'static_pages#not_allow'
get '/admin/user', to: 'static_pages#adminuser', as: "adminuser"
get '/index', to: 'static_pages#index'
get "/about" => 'static_pages#about', as: 'about'
get "/spp" => 'static_pages#spp', as: 'spp'
get "/deletep" => 'static_pages#deletep', as: 'deletep'
get "/setadmin" => 'static_pages#setadmin', as: 'setadmin'
get "/acceptp" => 'static_pages#acceptp', as: 'acceptp'
post "/index" => 'static_pages#searchp'
get "/searchpeople" => 'static_pages#searchpeople', as: 'searchpeople'
get '/signup', to: 'users#new'
post '/signup',  to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
root 'static_pages#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
resources :microposts do
    resources :comments, except: [:show, :edit]
    resources :likes
    resources :save_posts
    
  end
resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  Nhom bai tap lon Ruby on Rails
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "VIET-TRAVEL", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", index_path %></li>
        <% if logged_in? %>
        <li>
          <div class="dropdown navbar-component" title="Notification">
            <div class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <span class="fa fa-bell"></span>
              <% if @notifications.count != 0 %>
              <span class="button__badge"><%= @notifications.count %></span>
              <% end %>

            </div>
            <ul class="dropdown-menu noti-table" aria-labelledby="noti">
              <% @notifications.each do |notification| %>
              <li class="noti-comp">
              <%= link_to(notification.micropost) do %>
                  <%= image_tag notification.micropost.picture.url, class: "img-responsive img-circle noti-pic" if notification.micropost.picture? %>
                  <span>
                    <%= notification.notification%>
                  </span>
              <% end %>
              </li>
              <% end %>
            </ul>
          </div>
          <!-- end comment -->
        </li>
        
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% if current_user.admin == true %>
              <li><%= link_to "Admin page", admin_path %></li>
            <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<!--<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="#"><img src="./logo/logo.jpg" height="50"></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <form class="navbar-form navbar-left" action="{{ route('search.results') }}" >
        <div class="form-group input-group search-box">
          <input type="text" class="form-control" placeholder="Search..." name="query">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <span class="fa fa-search"></span>
            </button>
          </span>        
        </div>
      </form>      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li>
        </li>
        <li>
        
          <div class="dropdown navbar-component" title="Notification">
            <div class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="fa fa-bell"></span>
                <span class="button__badge"><%= @notifications.count %></span>
            </div>
            <ul class="dropdown-menu noti-table" aria-labelledby="noti">
            <% @notifications.each do |notification| %>
              <li class="noti-comp">
                
                  <img class="img-responsive img-circle noti-pic" src="img/avatar/ava1.jpg">
                <%= link_to notification.notification, notification.micropost %>
                  
              </li>
            <% end %>
            </ul>
          </div>
          <% end %>
        </li>
        <li>
          <div class="dropdown navbar-component">
            <div class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span class="fa fa-user"></span> My Account
            </div>
            <ul class="dropdown-menu" aria-labelledby="acc">
              <li><a href="#"><span class="fa fa-cog"></span> Settings</a></li>
              <li><a href="#"><span class="fa fa-sign-out"></span> Log Out</a></li>
            </ul>
          </div>
        </li>
      </ul>
  </div>
</nav> -->

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= render 'layouts/rails_default' %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<br><br>
	<div class="container">
		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>